; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

include listing.inc

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG188759 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188760 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG188768 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188769 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG188770 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188771 DB	'!x->ref.isStatic()', 00H
	ORG $+1
$SG185073 DB	'%s', 00H
	ORG $+1
$SG188784 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188785 DB	'int(d->alloc) == aalloc', 00H
$SG188786 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188787 DB	'isDetached()', 00H
	ORG $+3
$SG188788 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188789 DB	'x == d', 00H
	ORG $+1
$SG188797 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188798 DB	'd->data()', 00H
	ORG $+2
$SG195460 DB	'%s', 00H
	ORG $+1
$SG188799 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188800 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG188801 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188802 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG188803 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188804 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+5
$SG188805 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188806 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG188807 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG188808 DB	'd->size == asize', 00H
	ORG $+7
?qt_meta_stringdata_OptionsDialog@@3Uqt_meta_stringdata_OptionsDialog_t@@B DD 0ffffffffH ; qt_meta_stringdata_OptionsDialog
	DD	0dH
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	000000000000009eH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000008dH
	DD	0ffffffffH
	DD	01eH
	DD	00H
	ORG $+4
	DQ	0000000000000076H
	DD	0ffffffffH
	DD	01dH
	DD	00H
	ORG $+4
	DQ	000000000000007dH
	DD	0ffffffffH
	DD	01bH
	DD	00H
	ORG $+4
	DQ	0000000000000083H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	0000000000000087H
	DB	04fH
	DB	070H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	073H
	DB	044H
	DB	069H
	DB	061H
	DB	06cH
	DB	06fH
	DB	067H
	DB	00H
	DB	061H
	DB	063H
	DB	063H
	DB	065H
	DB	070H
	DB	074H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	070H
	DB	062H
	DB	048H
	DB	069H
	DB	067H
	DB	068H
	DB	06cH
	DB	069H
	DB	067H
	DB	068H
	DB	074H
	DB	069H
	DB	06eH
	DB	067H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	070H
	DB	062H
	DB	041H
	DB	064H
	DB	064H
	DB	072H
	DB	065H
	DB	073H
	DB	073H
	DB	041H
	DB	072H
	DB	065H
	DB	061H
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	070H
	DB	062H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	070H
	DB	062H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	046H
	DB	06fH
	DB	06eH
	DB	074H
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+1
?qt_meta_data_OptionsDialog@@3QBIB DD 08H		; qt_meta_data_OptionsDialog
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	027H
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	028H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	029H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	02aH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	02bH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG189654 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG189655 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG189656 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG189981 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG189982 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG189983 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG190308 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG190309 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG190310 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG191124 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG191125 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG191126 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG191490 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG191491 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG191492 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG191817 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG191818 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG191819 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG192144 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG192145 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG192146 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG192471 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG192472 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG192473 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG192823 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG192824 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG192825 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG193150 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG193151 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG193152 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG185072 DB	'containers incompatible for swap', 00H
	ORG $+15
$SG185074 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG185075 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG185076 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'P', 00H, 'o', 00H, 'c', 00H, 's', 00H, 00H, 00H
	ORG $+10
$SG185077 DB	'"', 00H, 'c', 00H, 'o', 00H, 'n', 00H, 't', 00H, 'a', 00H
	DB	'i', 00H, 'n', 00H, 'e', 00H, 'r', 00H, 's', 00H, ' ', 00H, 'i'
	DB	00H, 'n', 00H, 'c', 00H, 'o', 00H, 'm', 00H, 'p', 00H, 'a', 00H
	DB	't', 00H, 'i', 00H, 'b', 00H, 'l', 00H, 'e', 00H, ' ', 00H, 'f'
	DB	00H, 'o', 00H, 'r', 00H, ' ', 00H, 's', 00H, 'w', 00H, 'a', 00H
	DB	'p', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG193477 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG193478 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG193479 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG193804 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG193805 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG193806 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG185860 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG185861 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG185862 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG195459 DB	'invalid argument', 00H
	ORG $+15
$SG195461 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG195462 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG195463 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG195464 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ ; OptionsDialog::metaObject
PUBLIC	?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z	; OptionsDialog::qt_metacast
PUBLIC	?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; OptionsDialog::qt_metacall
PUBLIC	?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OptionsDialog::qt_static_metacall
PUBLIC	?staticMetaObject@OptionsDialog@@2UQMetaObject@@B ; OptionsDialog::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?on_pbHighlightingColor_clicked@OptionsDialog@@AEAAXXZ:PROC ; OptionsDialog::on_pbHighlightingColor_clicked
EXTRN	?on_pbAddressAreaColor_clicked@OptionsDialog@@AEAAXXZ:PROC ; OptionsDialog::on_pbAddressAreaColor_clicked
EXTRN	?on_pbSelectionColor_clicked@OptionsDialog@@AEAAXXZ:PROC ; OptionsDialog::on_pbSelectionColor_clicked
EXTRN	?on_pbWidgetFont_clicked@OptionsDialog@@AEAAXXZ:PROC ; OptionsDialog::on_pbWidgetFont_clicked
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@OptionsDialog@@2UQMetaObject@@B DB 030H DUP (?) ; OptionsDialog::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN12
	DD	imagerel $LN12+157
	DD	imagerel $unwind$?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@OptionsDialog@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@OptionsDialog@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@OptionsDialog@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@OptionsDialog@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@OptionsDialog@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'OptionsDialog::staticMetaObject'', COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 99
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B, rax
; Line 100
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_OptionsDialog@@3Uqt_meta_stringdata_OptionsDialog_t@@B
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B+8, rax
; Line 101
	lea	rax, OFFSET FLAT:?qt_meta_data_OptionsDialog@@3QBIB
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B+16, rax
; Line 102
	lea	rax, OFFSET FLAT:?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OptionsDialog::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B+24, rax
; Line 103
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B+32, 0
; Line 104
	mov	QWORD PTR ?staticMetaObject@OptionsDialog@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@OptionsDialog@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'OptionsDialog::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; OptionsDialog::qt_static_metacall
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 82
$LN12:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 83
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 84
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 86
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 4
	je	SHORT $LN9@qt_static_
	jmp	SHORT $LN10@qt_static_
$LN5@qt_static_:
; Line 87
	mov	rax, QWORD PTR _t$1[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	QWORD PTR [rax+384]
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 88
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_pbHighlightingColor_clicked@OptionsDialog@@AEAAXXZ ; OptionsDialog::on_pbHighlightingColor_clicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 89
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_pbAddressAreaColor_clicked@OptionsDialog@@AEAAXXZ ; OptionsDialog::on_pbAddressAreaColor_clicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 90
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_pbSelectionColor_clicked@OptionsDialog@@AEAAXXZ ; OptionsDialog::on_pbSelectionColor_clicked
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 91
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_pbWidgetFont_clicked@OptionsDialog@@AEAAXXZ ; OptionsDialog::on_pbWidgetFont_clicked
$LN10@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 96
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; OptionsDialog::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; OptionsDialog::qt_metacall
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 122
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 123
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 124
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 126
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 127
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN5@qt_metacal
; Line 128
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@OptionsDialog@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; OptionsDialog::qt_static_metacall
$LN5@qt_metacal:
; Line 129
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 130
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 131
	cmp	DWORD PTR _id$[rsp], 5
	jge	SHORT $LN7@qt_metacal
; Line 132
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 133
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 5
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 135
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 136
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@OptionsDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; OptionsDialog::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z PROC		; OptionsDialog::qt_metacast
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 114
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 115
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 116
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_OptionsDialog@@3Uqt_meta_stringdata_OptionsDialog_t@@B+168
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 117
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 118
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 119
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@OptionsDialog@@UEAAPEAXPEBD@Z ENDP		; OptionsDialog::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ PROC	; OptionsDialog::metaObject
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 109
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@OptionsDialog@@2UQMetaObject@@B ; OptionsDialog::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 111
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@OptionsDialog@@UEBAPEBUQMetaObject@@XZ ENDP	; OptionsDialog::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 139
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_optionsdialog.cpp
; Line 139
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
