; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28105.4 

include listing.inc

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG180239 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG180240 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG180241 DB	'qRegisterNormalizedMetaType', 00H
$SG173916 DB	'%s', 00H
	ORG $+1
$SG180566 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG180893 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG180567 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG180568 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG180894 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG180895 DB	'qRegisterNormalizedMetaType', 00H
$SG184209 DB	'%s', 00H
	ORG $+1
$SG181220 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG181572 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG181221 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG181222 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG181573 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG181574 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG181899 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG173915 DB	'containers incompatible for swap', 00H
	ORG $+3
$SG177588 DB	'x == d', 00H
	ORG $+5
$SG181901 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+12
$SG181900 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG173917 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG173918 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG173919 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'P', 00H, 'o', 00H, 'c', 00H, 's', 00H, 00H, 00H
	ORG $+10
$SG173920 DB	'"', 00H, 'c', 00H, 'o', 00H, 'n', 00H, 't', 00H, 'a', 00H
	DB	'i', 00H, 'n', 00H, 'e', 00H, 'r', 00H, 's', 00H, ' ', 00H, 'i'
	DB	00H, 'n', 00H, 'c', 00H, 'o', 00H, 'm', 00H, 'p', 00H, 'a', 00H
	DB	't', 00H, 'i', 00H, 'b', 00H, 'l', 00H, 'e', 00H, ' ', 00H, 'f'
	DB	00H, 'o', 00H, 'r', 00H, ' ', 00H, 's', 00H, 'w', 00H, 'a', 00H
	DB	'p', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG182226 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG182227 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG182228 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG182553 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG182554 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG182555 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG174703 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG174704 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG174705 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG184208 DB	'invalid argument', 00H
	ORG $+7
$SG184213 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG184210 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG184211 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG184212 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG177558 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177559 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG177567 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177568 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG177569 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177570 DB	'!x->ref.isStatic()', 00H
	ORG $+5
$SG177583 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177584 DB	'int(d->alloc) == aalloc', 00H
$SG177585 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177586 DB	'isDetached()', 00H
	ORG $+3
$SG177587 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177596 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177597 DB	'd->data()', 00H
	ORG $+6
$SG177598 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177599 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+6
$SG177600 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177601 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG177602 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177603 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+5
$SG177604 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177605 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+7
$SG177606 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qvector.h', 00H
	ORG $+3
$SG177607 DB	'd->size == asize', 00H
	ORG $+7
$SG178403 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG178404 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG178405 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_UndoStack@@3Uqt_meta_stringdata_UndoStack_t@@B DD 0ffffffffH ; qt_meta_stringdata_UndoStack
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	055H
	DB	06eH
	DB	064H
	DB	06fH
	DB	053H
	DB	074H
	DB	061H
	DB	063H
	DB	06bH
	DB	00H
	ORG $+6
?qt_meta_data_UndoStack@@3QBIB DD 08H			; qt_meta_data_UndoStack
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	ORG $+4
$SG178730 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+1
$SG178731 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG178732 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG179057 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG179058 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179059 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG179873 DB	'F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+9
$SG179874 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179875 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ	; UndoStack::metaObject
PUBLIC	?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z		; UndoStack::qt_metacast
PUBLIC	?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; UndoStack::qt_metacall
PUBLIC	?qt_static_metacall@UndoStack@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; UndoStack::qt_static_metacall
PUBLIC	?staticMetaObject@UndoStack@@2UQMetaObject@@B	; UndoStack::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QUndoStack@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QUndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QUndoStack@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@UndoStack@@2UQMetaObject@@B DB 030H DUP (?) ; UndoStack::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@UndoStack@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@UndoStack@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@UndoStack@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@UndoStack@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@UndoStack@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'UndoStack::staticMetaObject'', COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 66
	mov	rax, QWORD PTR __imp_?staticMetaObject@QUndoStack@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B, rax
; Line 67
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_UndoStack@@3Uqt_meta_stringdata_UndoStack_t@@B
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B+8, rax
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_data_UndoStack@@3QBIB
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B+16, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_static_metacall@UndoStack@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; UndoStack::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B+24, rax
; Line 70
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B+32, 0
; Line 71
	mov	QWORD PTR ?staticMetaObject@UndoStack@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@UndoStack@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'UndoStack::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@UndoStack@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; UndoStack::qt_static_metacall
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 58
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 63
	ret	0
?qt_static_metacall@UndoStack@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; UndoStack::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; UndoStack::qt_metacall
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 89
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 90
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QUndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 91
	mov	eax, DWORD PTR _id$[rsp]
; Line 92
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@UndoStack@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; UndoStack::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z PROC		; UndoStack::qt_metacast
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 81
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 82
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 83
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_UndoStack@@3Uqt_meta_stringdata_UndoStack_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 84
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 85
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QUndoStack@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 86
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@UndoStack@@UEAAPEAXPEBD@Z ENDP		; UndoStack::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ PROC	; UndoStack::metaObject
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 76
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@UndoStack@@2UQMetaObject@@B ; UndoStack::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 78
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@UndoStack@@UEBAPEBUQMetaObject@@XZ ENDP	; UndoStack::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File F:\QT_SW\5.12.4\MSVC2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 95
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File F:\qt_projects\qhexedit2-master\example\Debug\moc_commands.cpp
; Line 95
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
